VERSION="2.0.0" NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015" 

ACCOUNTS=[ 
"GDRBZLCRHRDI7IJYPFNQKBAMBGZBIY7D7BMOP2GZII7FOR5TSNXUBL62", 
"GBQO4XSIUPQE5SQNIFRRWURW4T7YARF4V4HBEU333664365V6GEXJGYF" 
] 

[DOCUMENTATION] 
ORG_NAME="plexo" 
ORG_LOGO="https://github.com/plexoassets/lexo/blob/main/XS.png" 
ORG_DESCRIPTION="Plexo es una empresa del sector cultural dedicada a la produccion y realizacion de eventos" 
ORG_PHYSICAL_ADDRESS="Reus" 
ORG_OFFICIAL_EMAIL="plexo@plexo.cat"

[[CURRENCIES]] 
code="LEXO" 
issuer="GDRBZLCRHRDI7IJYPFNQKBAMBGZBIY7D7BMOP2GZII7FOR5TSNXUBL62" 
display_decimals=6 
is_asset_anchored=false 
name="LEX"
desc="Un token para utilizar en eventos como forma de pago, premios o recompensas, intercambio, etc" 
conditions="Hay 1.000.000.000 LEX. Se distribuiran de diferente manera entre los usuarios de la red de Plexo" 
image="https://github.com/plexoassets/lexo/blob/main/XS.png"
# LEX (LEXO) Token was issued using the open and inclusive Stellar blockchain network. 
# Home Domain: https://github.com/plexoassets/lexo/blob/main/.well-known/stellar.toml
# LEX Token
