VERSION="2.0.0" NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015" 

ACCOUNTS=[ 
"GCAGQSW6TYDAP3AVOWKJVFFP5FGDYXVHEZRM2Q5KVNDOFFGJHI2G6OZA", 
"GBLF4PSXHKNFUMGO2K2OHY57STC32K7OZHBTYXY3L6KILPEHDEFO3LD3" 
] 

[DOCUMENTATION] 
ORG_NAME="MARFIL" 
ORG_LOGO="https://github.com/plexoassets/MARFIL/blob/main/XS.png" 
ORG_DESCRIPTION="MARFIL IS AN ASSET FROM PLEXO" 
ORG_PHYSICAL_ADDRESS="SPAIN" 
ORG_OFFICIAL_EMAIL="plexo@plexo.cat"
ORG_URL="https://github.com/plexoassets/MARFIL"

[[CURRENCIES]] 
code="MARFIL" 
issuer="GCAGQSW6TYDAP3AVOWKJVFFP5FGDYXVHEZRM2Q5KVNDOFFGJHI2G6OZA" 
display_decimals=6 
is_asset_anchored=false 
name="MARFIL"
desc="Un token ESCASO EXPERIMENTAL" 
conditions="unica emision de 1.000.000 de MARFIL" 
image="https://github.com/plexoassets/MARFIL/blob/main/XS.png"
# LEX (LEXO) Token was issued using the open and inclusive Stellar blockchain network. 
# Home Domain: github.com/plexoassets/MARFIL
# MARFIL Token
